### ISSUE TITLE
The TS membership expiry - how will this be handled? 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1013]
## 📋   Anything to add?

From the T&C:
https://ipfs.web3.party/ipfs/QmYDmtmDYUPR6wjukzaNytibeNnYs41s2co4tNzkUYdd5n

This is the paragraph that explains it: 
Membership shall expire as a result of withdrawal, death, or exclusion. Members may leave the Association by submitting written notice to the president at any time. Members may also be excluded from the Association with immediate effect if they fail to pay the membership contribution after two written reminders or for other important reasons, in particular acting in breach of the interests of the Association. The membership contribution for the current financial year is owed in any event, whether the member chooses to withdraw or is excluded.

These can prob best be answered by @krisjpi @Jeff-Emmett @GriffGreen 

## 🎉   Subtasks

- [ ] Direction from the Association on the when membership ends. 
For example:
- Do memberships all end on April 1, 2022
- what happens to members who join in Dec 2021, will they only have 3 months of membership?
- [ ] 
## 🤼‍♂️   Reviewer
@kristoferlund (who needs this to design TS dashboard)

**Comment by GriffGreen** [comment]
All of this needs to be discussed... probably in november as we will know more about the direction of the trusted seed by then

That said, these are my thoughts

Do memberships all end on April 1, 2022
- yes, unless they pay dues before that. 
 
What happens to members who join in Dec 2021, will they only have 3 months of membership?

Yes. I think we just keep it simple.

**Comment by Jeff-Emmett** [comment]
I would like to see further discussion on this topic led by @knobsdao & the Trusted Seed Circle in particular (when he is back from vacation, of course!), as well as the preparation of more data to make these decisions with appropriate context.

This topic also belongs in a larger frame of other CS revenue stream options - there is little likelihood that member dues alone will cover our required operating costs.  In that case, this topic should be discussed along with supplementary revenue streams from grants, contracts, and mutual collaborations between aligned projects.  This larger topic can be discussed along with the integration of a new hire into what we have been calling the "fundraiser" role, which would likely fall either into CS Ecosystems or CS Operations circle (or both).

On the topic of TS subscription fees, here are some questions I have thought up so far, and I would be happy to see more questions and data be surfaced to support the decision being made. (Dan, do you have this information corralled somewhere already perhaps?)

For the past year of activations:
- How many people have activated in the TS?
- How much revenue has the CS Assn received from activations?
- How many people have applied for & received a scholarship?
- How many people paid more than the minimum dues required? How much more did they pay?
- What is the cost for issuing scholarships?  (gas fees, etc on behalf of Griff & Giveth)
- What kind of overhead/admin is introduced each year with the inevitable churn of the re-subscription process? (e.g. comms campaigns, chasing people for re-contributing, token management, etc)

If we are considering the annual subscription route as a possible option, I think it would be prudent to do some community interviews and feedback rounds to understand the interests and motivations of the people who will be subscribing (or not) and weigh that into our decision as well. From my initial discussions last year when we introduced this concept (but largely did not communicate the annual payment aspect to our community), I heard from several core community members that they would be very unlikely to pay such a high fee on a yearly basis. Some even commented that having members pay to be included seemed very "old world" of a group that is innovating on public goods funding in so many ways. 

In my opinion, we make our own lives (as well as the lives of our community) significantly more difficult by adding in the annually recurring $450 subscription to the TS.  Dealing with angry people who pay full fees for 3 months of the year, having to follow up on people who are essentially donating to our cause to harangue them for more donations (else we take their tokens away!) does not seem like a scalable process - it looks like it would be a huge time sink for Dan and the Trusted Seed gardeners.  I would much rather see their efforts going into initiatives to improve the offerings of the TS rather than policing who has paid enough to be a part of it, on a recurring basis.

As an alternative to this annual subscription model, I would much rather see us continue to build more compelling tiers of participation into the Trusted Seed, such that people are naturally inclined and encouraged to continue re-upping their commitment to the TS, without the threat of their past participation and tokens being taken away from them. There are plenty of ways to build useful offerings from and for this community imo - we just need to put some work into it to make it happen.

I imagine there are many more great ideas of how we can make a compelling offer to the TS to ensure donations (and other revenue streams) continue to roll in, and I would be happy to be a part of some brainstorming sessions to see how we can create true win-win-win scenarios for the CS Association, the Trusted Seed DAO, and our community.  🙏

**Comment by Jeff-Emmett** [comment]
Here are some of the answers to the questions above, from initial forays into the data:

![image](https://user-images.githubusercontent.com/46964190/135201528-eb5bc960-09fa-489b-aedb-f68e9624ede8.png)

@knobsdao, I added some links to the Notion doc under CS Operations with the spreadsheet I was playing around in, if it is of any use to you!  I will probably do some other CSTK analysis in there as well, rather than mess up the official recording sheets ;)

**Comment by GriffGreen** [comment]
looks like we raised ~180k thru this funding stream in the last 8 months...  that's pretty good... It has been paying the core team's salary, month after month.

The airdrops more than cover the 450 DAI and it gives people a yearly reminder that they can support us. I think that is the biggest benefit :-D

**Comment by mafer-labs** [comment]
I'm working on a proposal document with all the needed information for discussion: https://docs.google.com/document/d/1M8nlOX8ymWVhCZkNCe5y-CAhlv1LadRAgCTrhnatoZU/edit#

**Comment by mafer-labs** [comment]
I have added to the document the current proposals that have been discussed. The doc is open for team discussion and suggestions.

**Comment by kristoferlund** [comment]
I clarified my proposal a bit.

Simple as this:
- Jan 1 – Jun 30: Pay 450 for full year
- Jul 1 – Dec 31: Pay 225 for half year

**Comment by tamarandom** [comment]
Thank you @mafer-cordovas for wrangling this together. I added support for @kristoferlund's suggestion in the doc even though, ultimately, it's the Board that needs to approve the solution.

**Comment by mafer-labs** [comment]
Pending: let's rock the vote! (board)

**Comment by mafer-labs** [comment]
Discussion doc sent to the board. @mzargham @krisjpi @Jeff-Emmett @iviangita @GriffGreen  and coach b.

**Comment by mafer-labs** [comment]
New document for drafted notice: https://docs.google.com/document/d/1_cWj3PeysBXHorjgUcgP7zbscH8bIw9HkLrJkzR1Y24/edit#

Campaign project: https://www.notion.so/giveth/Renewal-Campaign-8e00669e82a34a859136eb9fe4318f0a

**Comment by tamarandom** [comment]
DEADLINE: This communication about the membership extension must go out on Thursday, Match 17th. (That is only 2 weeks before all memberships expire).

**Comment by GriffGreen** [comment]
Did it go out?

**Comment by tamarandom** [comment]
I did not receive the email yet.

**Comment by mafer-labs** [comment]
1st email notification has been sent successfully and by the time of this update, 4 members have sent their renewal dues. 

The renewal process for the current period stays as follows:
1. Deadline to renew membership is March 31st, as stated on the T&C.
2. A 3-month extension after the expiration day will be granted.
3. Members can extend their membership by paying extra dues. (More details to be added)

A 2nd renewal reminder must be sent and a 1:1 reach out campaign will be executed by the gardeners @mafer-cordovas @YineisyM

**Comment by YineisyM** [comment]
We need to create the next messages: the second email and 1:1 contact. @mafer-cordovas

**Comment by tamarandom** [comment]
(Note: The new terms for the T&C is being tracked in issue #1247)

**Comment by mafer-labs** [comment]
2nd email notification has been sent successfully and by the time of this update, +22 members have sent their renewal dues.

The renewal process for the current period goes as follows:

- The deadline to renew membership is March 31st, as stated on the T&C. A 3-month extension period has been granted, and the new deadline is June 30th.

- The new date after paying renewal dues is exactly 1 year. 

With this update we close this issue, and a new one will be created to follow up the renewal process.
