### ISSUE TITLE
Jess handover doc 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1092]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@iviangita 

## 🔗   Work doc - inspirational links
(Ivy has the template to share!)

**Comment by jessicazartler** [comment]
Heya @tamarandom @iviangita just wanted to check in to see if there is anything in particular that could be helpful further? I am STILL finishing some backlog tasks, everything in Github - handed off the Regen partnership and will still be supporting that for some time... Just finished Ekene's review - any thing else that could be helpful for you ? Let me know, happy to draft something - otherwise everything in Github + supporting the partnership is pretty much it that I can think of... thanks!
