### ISSUE TITLE
Implement Giveth shop design in WP shop

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/iteration0#1119]
## First page

![image](https://user-images.githubusercontent.com/9698363/145207988-286dc5eb-318f-4c85-8866-62003512e572.png)

- Giveth store logo
- Change to Giveth colors and fonts wherever possible
- Hero banner above products
- Hide unnecessary info (default sorting, etc)
- Set footer content
- Giveth swag shop: copy footer from https://giveth.io/

![image](https://user-images.githubusercontent.com/9698363/145208053-5d75fbf1-5dc6-4994-9349-ecf46a529359.png)

## Cart

![image](https://user-images.githubusercontent.com/9698363/145208159-0a57211e-dd8a-47a0-ad0c-882077cf40e8.png)

- Adjust theme colours

## Payment
![image](https://user-images.githubusercontent.com/9698363/145208201-d6f29525-e914-475d-b866-d24bd85b59bd.png)

- Add info text at top
- Rearrange blocks
- Add short infographic, telling the user to connect to the right network etc.

**Comment by kristoferlund** [comment]
## First page

![image](https://user-images.githubusercontent.com/9698363/145207988-286dc5eb-318f-4c85-8866-62003512e572.png)

- Store logo
- Hero banner above products
- Hide unnecessary info (default sorting, etc)
- Set footer content
- Giveth swag shop: copy footer from https://giveth.io/

![image](https://user-images.githubusercontent.com/9698363/145208053-5d75fbf1-5dc6-4994-9349-ecf46a529359.png)

## Cart

![image](https://user-images.githubusercontent.com/9698363/145208159-0a57211e-dd8a-47a0-ad0c-882077cf40e8.png)

- Adjust theme colours


## Payment
![image](https://user-images.githubusercontent.com/9698363/145208201-d6f29525-e914-475d-b866-d24bd85b59bd.png)

- Add info text at top
- Rearrange blocks
- Add short infographic, telling the user to connect to the right network etc.

**Comment by kkatusic** [comment]
I will write here in comment which file contains which change:

- Counter in main navigation in "Cart" link. "Cart" link has been defined with custom class via administration: `cart-main-link` on link `http://kristoferl.sg-host.com/wp-admin/nav-menus.php` logic is in file: `wp-content/themes/generatepresschild/inc/woocommerce/woocommerce-number-items-cart.php`
- Hidden sorting via css file: `wp-content/themes/generatepresschild/style.css`
- Footer changes, hidden generatepress bar: `wp-content/themes/generatepresschild/style.css`, adding new one: `wp-content/themes/generatepresschild/inc/theme/footer.php`
- Order thank you page intro text: `wp-content/themes/generatepresschild/inc/woocommerce/woocommerce-order-checkout.php`
- Order rearrange blocks. This function is done by jQuery help because we can change WooCommerce template file and make reorder, but we can't put "Pay with CSLOVE" in middle of "order details" and "shipping info", that changes can be only made inside payment ETH plugin. Swap is in file: `wp-content/themes/generatepresschild/js/require-footer.js`
- Adding infographic: `wp-content/themes/generatepresschild/inc/woocommerce/woocommerce-order-checkout.php`
