### ISSUE TITLE
Reevaluate the Discord server for areas of improvement 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#1161]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ]

**Comment by tamarandom** [comment]
@YineisyM will you please add more details so it is clear what work is expected from @Vyvy-vi on this one.

**Comment by YineisyM** [comment]
Hey @tamarandom actually, I'm not sure... Griff opened this issue. I think it is because @mafer-cordovas asked about having a bot like the one in the TEC:

![image](https://user-images.githubusercontent.com/88781843/172161874-204d2ced-460c-48cd-9271-20b19596b287.png)

And also, it was related to having a landing similar to this one: https://discord.tecommons.org/ 

But what **definitely needs to be fixed** in Discord is the CollabLand bot that it's currently connected in the cstk-activation channel (but we should rename it to trust-activation channel). It should assign the Trusted Seed member role and grant access to specific channels by reading the amount of TRUST on people's wallets, but it is not working.

**Comment by YineisyM** [comment]
I fixed the CollabLand bot so people can now claim their Trusted Seed role via the 💚trust-activation channel

**Comment by tamarandom** [comment]
Great!
