### ISSUE TITLE
Develop The CS SEO as a content finding strategy

### ISSUE THREAD

**Issue by Ekeneodigwe** [commons-stack/iteration0#1251]
## 🎉   Subtasks

- [This will guarantee  that all content is easy to find & tagged correctly in all places thereby supporting discoverability] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Closing old issues.

**Comment by YineisyM** [comment]
I agree we can improve our SEO strategy and of course create content pieces that support visibility as is mentioned in this issue. I'm not seeing a link that tells me what Ekene was working on in this issue. 

I asked @usama9500 and he mentioned he has a basic understanding of how it works and I have some knowledge on how to do it too (not on technical SEO), however, this is a task that requires a large amount of time and also money because specific tools are needed to analyze results and searching process. 

It is about not only creating a SEO strategy but also build a process to continue optimizing. A basic monthly SEO plan is about:

- Devote time to keyword research related to Commons Stack/ or in our industry general.
- List blog post ideas that leverage opportunistic keywords.
- Identify blog posts that can be updated or refreshed.
- Identify other SEO opportunities across our channels (YouTube, Social media in general).
- List content ideas in a Search Insights Report: This depends on A) how much content we can publish and B) how often we'll release new reports.
- Assign this content ideas to probably Usama to develop them since he is the 
- Track progress at the end of each month.

And before doing this we should discuss our objectives, will it be focused on?

- **On-page SEO:** This SEO focuses on the content that's actually on site pages, and how to optimize it to boost the website's ranking for specific keywords.
- **Off-page SEO:** This SEO focuses on links directed to the website from elsewhere on the internet. The number of backlinks a site has from reputable sources helps you build trust with search algorithms.
- **Technical SEO:** This SEO focuses on a website's backend architecture, like site code. Google cares just as much about technical set-up as it does content, so this position is important for rankings.

Based on all these details we need to consider how high a priority this task can be in our current workflow if we can handle it or even consider hiring an SEO expert who can do it. @iviangita 

**More info about this topic:**
[How to Create an SEO Strategy](https://blog.hubspot.com/marketing/seo-strategy)
[How to create a Search Insights Report](https://blog.hubspot.com/marketing/how-to-create-search-insights-report)

**Comment by YineisyM** [comment]
I agree we can improve our SEO strategy and of course create content pieces that support visibility as is mentioned in this issue. I'm not seeing a link that tells me what Ekene was working on in this issue. 

I asked @usama9500 and he mentioned he has a basic understanding of how it works and I have some knowledge on how to do it too (not on technical SEO), however, this is a task that requires a large amount of time and also money because specific tools are needed to analyze results and searching process. 

It is about not only creating a SEO strategy but also build a process to continue optimizing. A basic monthly SEO plan is about:

- Devote time to keyword research related to Commons Stack/ or in our industry general.
- List blog post ideas that leverage opportunistic keywords.
- Identify blog posts that can be updated or refreshed.
- Identify other SEO opportunities across our channels (YouTube, Social media in general).
- List content ideas in a Search Insights Report: This depends on A) how much content we can publish and B) how often we'll release new reports.
- Assign this content ideas to probably Usama to develop them since he is the 
- Track progress at the end of each month.

And before doing this we should discuss our objectives, will it be focused on?

- **On-page SEO:** This SEO focuses on the content that's actually on site pages, and how to optimize it to boost the website's ranking for specific keywords.
- **Off-page SEO:** This SEO focuses on links directed to the website from elsewhere on the internet. The number of backlinks a site has from reputable sources helps you build trust with search algorithms.
- **Technical SEO:** This SEO focuses on a website's backend architecture, like site code. Google cares just as much about technical set-up as it does content, so this position is important for rankings.

Based on all these details we need to consider how high a priority this task can be in our current workflow if we can handle it or even consider hiring an SEO expert who can do it. @iviangita 

**More info about this topic:**
[How to Create an SEO Strategy](https://blog.hubspot.com/marketing/seo-strategy)
[How to create a Search Insights Report](https://blog.hubspot.com/marketing/how-to-create-search-insights-report)
