### ISSUE TITLE
Draft light-weight "Association Handbook" as a way of defining our common work traditions

### ISSUE THREAD

**Issue by Kisgus** [commons-stack/iteration0#15]
## 📋   Description

Produce a short write up of proposed internal work traditions

## 🎉   Definition of done

- [x] Draft and basic idea is shared and approved by Griff
- [x]  Draft is iterated and discussed with @lorelei1 and @krrisis 
- [x] All other team-members review, iterate and edit handbook
- [x] Final version is agreed upon and we start following the handbook

## 🤼‍♂️   Reviewer

@GriffGreen @lorelei1 @krrisis 
@Rest of core team

## 🔗   Links

Rough draft to be iterated shortly with Griff

https://docs.google.com/document/d/1D2m65oW2EmMMOg0oQuDPTpz-0mF1A5KzTk5GNgn6K0A/edit?usp=sharing

**Comment by Kisgus** [comment]
Added draft link: https://docs.google.com/document/d/1D2m65oW2EmMMOg0oQuDPTpz-0mF1A5KzTk5GNgn6K0A/edit#

**Comment by Kisgus** [comment]
Im blocking this issue until we have consent on my proposed process:



——————————————————
🏄‍♂️Process for ALL team members
——————————————————

Every quarter:

- Just like we just did now Griff with help from team defines and agrees on milestones and prioritizes and put it into Github, this means we will always have an updated quarterly roadmap visualized like we have now 


Every month:

- Before each month each member propose their Giveth milestone and Griff + team approves it. Here it has to be clear which specfiic tasks are related to which milestones

- In the end of each month we have a public review showing the progress of that month on the milestones, as well as an internal evaluation, 

a) on what went well
b) what didnt
c) which new actions should we take

Every week:

- Focused meeting only focusing on if any team members are blocked

Every day:

- Write what you are doing every day. Can be in beginning or end of each day. 

—————————————
🤼‍♂️Circle specific process
—————————————

Leads: I am personally fan of having a dedicated lead for each circle, but maybe each circle has different ideas regarding this. I can imagine this Circles could do stuff like:

Weekly: This can be different for each circle, but may include weekly coordination, like the current Comms / Fundraising coordination calls etc.

Monthly: Iterate prioritizes with Griff, agree on monthly milestone coordination and creation of issues, so basically agreeing what to prioritize for the next month

———————————————
⚖Decision-making protocol
———————————————

Assignees to issues

- The person assigned to a task is the repsonsible person to carry that out. This is because the team trust that the person is capable of carrying it out, which also means they are able to make specific execution related decisions.

Reviewers to issues

Reviewers are, upon request of the assignee, summoned to help the assignee to qualify the solution. Each issue needs (usually) at least 1 reviewer assigned.
So the reviewer is basically serving the assignee, which also means that in the end it is the call of the assignee of to execute on stuff and get it out.

Dispute resolution

If a circle believes that a circle lead or assignee is making wrong decisions or whatever and it is not solved between assignee and reviewers we have the protocol of:

a) Its discussed and consensus is heard in the circle
b) If still not solved we bring it up on the monthly evaluation and in the end its the opinion of the team that counts

**Comment by lorelei1** [comment]
@krrisis @lorelei1 @Kisgus will sync up together enough to make a final agreement on weekly+monthly meeting process during next week's monday meeting

**Comment by lorelei1** [comment]
GOVERNANCE MEETING:
- Loie only would facilitate if on an as-needed, make a proposal beforehand, basis.
- Kris wants to see regular but nobody wants to facilitate it regularly so proposal is to incorporate it into monthly review meeting

TACTICAL MEETING:
- before: each person reads all github issues they're attached to, and knows a few they need to inquire about (identify with blocked label or move it into review column)
- during: 30 min max. SHORT check in 5 min. Then each person gets 5 min total to say what they are blocked on, need review, and have whatever dialogue abt those things. Pass it to next participant for their 5 min. Gus shows on his screen GH filtered by name of team mate who is speaking
- after: remove blocked labels, move issues from review back to in progress or closed. DM the ppl you identified needing sync/work sessions this week to get unblocked (ie Loie and Kris have a sync call)

MONTHLY:
- monthly board or no?
- monthly meeting & having monthly time boxed things, we are all in agreement on
- disagreement is on how it is visualized: monthly labels instead of monthly board (so you can filter on August for example)
- proposal monthly planning meeting is at least 5 days before start of new month
          - amendment! we schedule a retrospective meeting and a planning meeting one after another (within same day or 1 or 2 days) around the 30th to 2nd of the month @Kisgus schedule these
- month end review meeting ~ start with team only, maybe in future months we can start doing public review meeting
- Gus facilitates monthly meetings

QUARTERLY:
- don't need to plan a new quarterly just yet
- Griff and Gus pretty much did quarterly planning already in the end of July
- Kris suggests that we don't have it on a strict time schedule
- hard to talk about this one w/o Griff

CIRCLES:
- We don't need to use them - the pieces we really keep from Holacracy are Advice Process, Roles, and Domains
- We have the topic-channels like Budget, Community Management etc where one can ask advice of a circle's topic
- Loie is missing a bit the organic advice process - the wisdom-shaping that happens by just talking with one another
- Proposals: 
       - Every other week have the extra 30 minutes added to tactical meeting? (Don't use it unless there are topics) @lorelei1 schedule these
       - Friday cool down meeting

**Comment by Kisgus** [comment]
Here is done v1, please feel free make edits in https://docs.google.com/document/d/1D2m65oW2EmMMOg0oQuDPTpz-0mF1A5KzTk5GNgn6K0A/edit#


[Commons Stack Handbook.pdf](https://github.com/commons-stack/iteration0/files/5118733/Commons.Stack.Handbook.pdf)
