### ISSUE TITLE
Decide if we should work on our internal culture with Kate

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#220]
## 📋   Anything to add?

We have a lot of new people coming into the team and we are about to double down on working with contributors... we are bound to end up with conflicts and such... It might be good to start working with Kate to create a conflict management system and start following the Ostrom Principles

## 🎉   Subtasks

- [x] everyone review this doc, feel free to ask questions and make comments, we need a strong yes from everyone for it to work: https://docs.google.com/document/d/1TjyNtyCymaOyZYTPAVTJ0yFU2VYndpKqBQ31w_mmy00/edit?usp=sharing
- [x] Kris
- [x] Jess
- [x]  Jeff
- [x] Gus
- [x] Livia
- [x] Griff
- [x] Tamara
- [x] Dan
- [x] Get Kate to respond to the comments in this thread

## 🤼‍♂️   Reviewer

@liviade1 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1TjyNtyCymaOyZYTPAVTJ0yFU2VYndpKqBQ31w_mmy00/edit?usp=sharing

Pdf Version exists if you want to see it :-D 
[Briefing for The Common Stack(1).pdf](https://github.com/commons-stack/iteration0/files/5477279/Briefing.for.The.Common.Stack.1.pdf)

**Comment by tamarandom** [comment]
Hey, can someone please check my box. I am unable to edit directly.

**Comment by jessicazartler** [comment]
Just did @tamarandom :D

Great document, I think there are a few questions before deciding on this process... this is a huge investment of time and resources and is definitely valuable... but also, based on current workloads I am not sure what priority we want to place on this as 5 hours may be a little challenging in the next few weeks (2 x 2hr workshops + 1 hr 1 on 1s) = 5hrs x 7/8 team members a full work week.. 

It would be helpful to have an outline of the workshops as well to get a little preview of what this will involve... is there one we could look at?

Perhaps there is a time investment that can happen in iterations or smaller chunks - or spread the workshops over two months, and I think it could be helpful to look at what are the highest priority needs to develop as far as agreements, expectations, boundaries, triggers etc. and any process by which anyone would break an agreement that is most supportive for all of our work and relationships and work from there, rather than starting from a process and going the other way. Perhaps an a-sync list of what we think is important that needs discussion outside of the handbook?

That being said, I am definitely open to whatever the team decides in doing this work and think these discussions are incredibly important - appreciate the initiative

**Comment by tamarandom** [comment]
Thank you, Jess.

Well articulated. 

Speaking from the perspective of one brand new to the group I find myself trusting in the collective wisdom and experience of those of you who have worked together for much longer. If one no =  no go, then I’m a yes, but I concur with the question you raise about prioritization against the current workload to reach the TEC go-live and the timing for such an initiative.

**Comment by GriffGreen** [comment]
The timing is never going to be good for this i'm pretty sure, I actually think it makes sense to get this going ASAP before things get crazy with the launch and after the launch... there is always a feeling that once we hit the TEC launch milestone everything will slow down.. but that has never been what i have seen :-D It usually gets even crazier after launch and takes months to calm down.

I have definitely seen our current system fail, and cost us countless hours of discussion and even led to the point that people left the org because of it.

Not only do we need this as a team, what helps me want to pull the trigger asap is the ability to learn potential tools for the TEC and the rest of our work :-D 5 hours per person worth of Team Culture research and learning applied to our own work seems like an easy win.

**Comment by jessicazartler** [comment]
Agree about it getting crazier after the launch! Sure, requesting we just outline some goals and immediate needs for the process and break up the sessions in 2 sprints

**Comment by Jeff-Emmett** [comment]
I'm on board to ensure the team is on the same page with expectations & agreements!  

As is often the case, shorter calls & sessions are preferable for my schedule (2 hours is doable, but 1-1.5 hour preferred where possible)

**Comment by KateBee1** [comment]
Hi everyone, great comments about the process I proposed. Thanks a lot for taking the time. I'm hearing that it can seem like quite a lot of time dedicated to something without clear deliverables for each part. 

On time commitment:
The calls can be 45 mins and if we don't need the full time we won't use it. These are 'Discovery Calls' where I get to know more about the team and how it operates but most importantly about you, and where you're at. 

After the calls I will send you the design of the two workshops - they need to be 2 hours as 1.5 hours is not enough to get through much content (sorry @Jeff-Emmett, hopefully we can make them at a time where you are not call-overloaded). Just as a note usually these workshops are in person and take half a day. Given we can work with virtual call technology we can shorten it down. 

We **can** spread the workshops out through - we can do the first after I've had my checkin calls with each of you. Hopefully in 1-2 weeks. Then we can do the second late December before the holidays or later as we sense into the need. 

Deliverables from the calls: 
- I understand more about the need of the team and each individual regarding 'relational work'. 
- You feel seen, heard and respected. 
- I can share exercises with you or more reading if you're up for it.
- I can use what I learn to plan the workshops in more detail.

On workshops: 
It's really important that we practice together someone of the soft skills before prototyping the structural elements (e.g a team agreement on conflict resolution). Without creating shared intention and understanding and practicing the mindsets that enable us live our principles, agreements can become 'written rules' a file relegated to a dusty drawer, instead of culture via living social norms. I'm keen to discuss this with you all when we meet one on one as I'm sure many of you have interesting opinions on governance.

Deliverables from the workshops
- Together the team learn and practice tools, mindsets for better relational fabric
- Individually they leave with more information about their strengths and learning edges 
- Together we make a living 'social contract' version of a team agreement 'How we agree to be together'
- Prototype the start of an approach to a conflict resolution process 

Also if anyone is interested in the rest of the pillars that weren't included on that document let me know and I'll send them your way!

**Comment by jessicazartler** [comment]
Thank you @KateBee1 for your feedback! Will leave it to @GriffGreen @liviade1 how we want to proceed.

Also we have these two existing resources to draw from:

Current practices in the Commons Stack Handbook, which we can expand on the cultural elements
https://docs.google.com/document/d/1D2m65oW2EmMMOg0oQuDPTpz-0mF1A5KzTk5GNgn6K0A/edit#

Token Engineering Commons has a working conflict management group that has created documentation that we could draw on and also use as an arbitrator or neutral advisor in the case any conflicts come up:
https://docs.google.com/document/d/1yrEcPoOW8Q1qDE-YWWF0MhXlcvpiMk0jmdQx25nfZ6k/edit#heading=h.4qr126s3qfr1
