### ISSUE TITLE
Refine issues for this sprint!

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#257]
## 📋   Anything to add?

Help each member of the team go thru their issues and make epics and refine the issues so we know what part of the current issues can be achieved during this 2 week sprint... so that we can plan on closing all the issues during the review cal! 

## 🎉   Subtasks

- [ ] Schedule calls with everyone
Have calls with all these peeps:
- [ ] Kris
- [ ] Dan
- [ ] Griff
- [ ] Livia
- [ ] Jeff
- [ ] Jess

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by tamarandom** [comment]
duplicate of #253 

Even though, technically, that during those working sessions we were more focused on entire work load and breaking those down into themes epics and sprint-executable issues rather than issues specific to this sprint. ;\ These two tasks are intertwined. A handful of those sessions ran to be 2 and even 3 hours long as they were. My thinking is that refining issues is a process we can refine over the next sprint. It should become automatic as part of our workflow. ;)
