### ISSUE TITLE
Jess - Join the Swiss Association, make issues, apply for scholarship

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#477]
- [x] Get 450 DAI and >0.01 ETH in your CSTK address
- [x] Follow thru on the App (wait till Tuesday to start) https://develop--tech-dapp.netlify.app/contribute
- [x] Make at least 1 issue here! https://github.com/commons-stack/tech-dapp/issues/new
- [ ] Apply for the scholarship if you would like (Griff will work on this, in this sprint, will be ready by the weekend)

**Comment by jessicazartler** [comment]
<img width="889" alt="Dapp Page 1" src="https://user-images.githubusercontent.com/43972522/105645918-bd46a500-5e6a-11eb-9e47-800c5387aaed.png">

-Connect wallet as a CTA twice is unnecessary

-Perhaps instead of having the terms/statutes on the first page, we just put a download button in the section where you sign with your wallet instead -- I think it might be clearner, however, steps or a heads up on process would be good, or a walk through video.

-Maybe the text part could be edited: Donate & Join the Commons Stack Swiss Association - can they donate without joining the association if they don't want to?

-Also terminology "ABC Hatch Phases" is a bit weird - maybe access to future Commons launches 

-What is "Member of the Trusted Seed Registry?" - Are these supposed to be steps in the app?

-Perhaps we should have a message from the association before the terms & conditions come up -- like welcome to the membership process or something nice

-Terms and conditions section: "The Association promotes this, in particular, by providing financial
support to association members who suffer a financial loss as the result of a legal proceeding
against them due to participation in or membership of such a project." <--- this sounds pretty bad, could we say "members in the case they suffer financial loss" -- and is this promising financial support, should we rather promise legal support or neither? Guessing you ran this by the lawyers, but as written sounds like it's 100% sure they are getting sued

-"a one-off member benefit of up to CHF 10’000.00 francs in order to cover reasonable attorney fees for defense purposes." -- how will this be determined?

**Comment by jessicazartler** [comment]
<img width="938" alt="Dapp 2" src="https://user-images.githubusercontent.com/43972522/105650568-179f3000-5e82-11eb-93ed-b57d4392a579.png">

Screen weird -- on 100% but can't see the bottom button unless I go to like 90 or 75% screen size

**Comment by jessicazartler** [comment]
<img width="940" alt="Dapp 3 Not White Listed" src="https://user-images.githubusercontent.com/43972522/105650593-28e83c80-5e82-11eb-8f11-039a9a49f6d6.png">

Hey walking through the Dapp/Swiss association process and it says my address is not whitelisted even though I have CSTK? - can ya'all help? Also putting comments on the walk through in the Github issue

I also wonder UI/UX wise if we should stop them from donating at this point — or if there is a way to allow them to donate and it gets held until Trusted Seed approval, but I realize then this would require a return mechanism.. just a thought for discussion..

@GriffGreen see feedback here and above thanks!

**Comment by jessicazartler** [comment]
Finished! @GriffGreen Just two last things:

1) The SM sharing is great
2) Will we send an email confirming that people have joined the association?

Apply for scholarship will be a special section on Giveth? Happy to give feedback on the UI/UX or walk through for the scholarship when it is ready
