### ISSUE TITLE
Ata - Join the Swiss Association, make issues, apply for scholarship

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#480]
- [ ] Get 450 DAI and >0.01 ETH in your CSTK address
- [ ] Follow thru on the App (wait till Tuesday to start) https://develop--tech-dapp.netlify.app/contribute
- [ ] Make at least 1 issue here! https://github.com/commons-stack/tech-dapp/issues/new
- [ ] Apply for the scholarship if you would like (Griff will work on this, in this sprint, will be ready by the weekend)

**Comment by tamarandom** [comment]
Hey @ataberkcasur ! Please use this NEW URL! https://member.commonsstack.foundation/pay-dues

**Comment by tamarandom** [comment]
Closing. This was opened back when we needed a hand  finding bugs in the dApp. I've sent @ataberkcasur the following three links so that he can apply at his leisure : 

Apply for Trusted Seed Swiss Membership
https://member.commonsstack.foundation/

Trusted Seed Swiss Membership Scholarship Application
https://medium.com/commonsstack/trusted-seed-swiss-membership-scholarship-application-f2d07bc2fc90

Trusted Seed Swiss Membership walkthrough video
https://www.youtube.com/watch?v=03HQCF12Qeg
