### ISSUE TITLE
IPFS and DNS <-- need automated solution 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#498]
## 📋   Anything to add?

The issue is this: 
Every time we sync with Printful and publish the updates to our dshop stores we need to update DNS TXT record _dnslink.shop with the latest hash. Example, "dnslink=/ipfs/QmbEM1R1hQHAdGeqA2EUQ7JPYpWrsveXUyTxQSN7QfSDcJ/". 

Note that this would be for both cslove.commonsstack.org and shop.commonsstack.org :
_dnslink.cslove _dnslink=/ipns/cslove.commonsstack.app
_dnslink.shop _dnslink=/ipns/shop.commonsstack.app

**How can we make that more automatic? Here is the suggestion from Ludo:**

Ludo(Spain), [26.01.21 10:43]
Have a secondary domain like commonsstack.app
Put that domain under route53 or CloudFlare management.

On commonsstack.org :
Have the dnslink on commonsstack.org like that => _dnslink.cslove _dnslink=/ipns/cslove.commonsstack.app

Have the Dshop backend connected to route53 or Cloudflare

Ludo(Spain), [26.01.21 10:43]
you will never need to change the records on commonsstack.org

Ludo(Spain), [26.01.21 10:43]
and they will be updated automatically on commonsstack.app

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
@krisjpi Can we have a quick call to talk through next steps for this. There are frequent updates to the store and each one requires a manual change to our dns records. Sub-optimal. ;) I know you can help, let's find out when this piece of work can be planned.

**Comment by tamarandom** [comment]
Hey @skylar745 ! I passed @krisjpi your telegram handle so he can reach out to you about technical details.

**Comment by dysbulic** [comment]
¿Have you considered forwarding to an ENS domain?

You could set a `CNAME` from `cslove.commonsstack.app` to `shop.cstack.eth.link`. You can then set the IPFS value that resolves to via the blockchain.

It seems like the site could be built, uploaded to IPFS, and the ENS entry updated via a GitHub action.

The significant issue would be gas fees. ENS domains are on mainnet, and just to test I reserved `cstack.eth` and put up a static page: [cstack.eth.link](//cstack.eth.link). It was $50 to update the content location.

Also, at this point in time I've getting an error when trying to resolve [cstack.eth.link](http://cstack.eth.link). I'm hoping it's just because I've recently initialized everything.

**Comment by tamarandom** [comment]
Hi @dysbulic! Thank you for the suggestion and as far as I know we have not considered that as a solution.

**Comment by tamarandom** [comment]
Not going to happen. Closing this issue for good.
