### ISSUE TITLE
Finalize slide deck

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#56]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by krrisis** [comment]
We last discussed the existing decks could be used - eg the one I made bitangels and can be tweaked for a specific person. I will continue to work on updated visuals to be used in slide decks, that issue already exists, see #47 
If this is not assigned to someone I propose to close it as it's otherwise one of those that will lay dormant here for a year :)

**Comment by krrisis** [comment]
Made this in a more specific task for myself for October, see #127
