### ISSUE TITLE
Define the boundaries around the Trusted Seed especially around the Legal Association

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#646]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Update : 

"Activate your Trusted Seed membership by joining the Legal Association"
You are not part of TS until you join the Association
Trusted Seed score will be burned (when?) BUT it will be recorded so that when you  do join the legal association it will be be counted. 

@krisjpi and @knobsdao to continue the conversation....

**Comment by knobsdao** [comment]
Continuing in #670.
