### ISSUE TITLE
Begin Trusted Seed Narrative Upgrade 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#8]
Dan to flesh out the plan for this

This is extremely difficult to pull off without a full-time community manager

:-D 
Authentic Engagement events
Getting the advisors active in the Trusted Seed

We also had this very awesome workshop on it that has a lots of ideas: https://docs.google.com/document/d/1OuDRWxQGQuRtWKWYRf3u-DuFk9eW6YbniLNlUGyMaAc/edit?usp=sharing

**Comment by jessicazartler** [comment]
**@liviade1 @jessicazartler** 
Had a **meeting** today to discuss and **brainstorm ideas around engaging the Trusted Seed** some ideas:
-Continue the Trusted Seed Spotlight
-Survey members to ask about why they are here, what value are they seeking i.e. reputation, access, connections
-Improve the process/flow to channelize time contributions
-Consider clear partnership & contribution agreements to outline token swaps/contributions in hours with unofficial understanding of receiving praise --> CSTK tokens
-We love Griff's idea to airdrop tokens
-We should be more inclusive and lower the barrier to entry 
-Feeling seen & heard is very important on making people feel good and encourages reciprocity
**OVERALL THOUGHTS**: Let us shift our thinking and focus on how and what we can give to our community, rather than what does the Commons Stack need

**Comment by liviade1** [comment]
- understanding what can we give by listening to their needs 
- with trust and reciprocity and a small community we could start experimenting a lets? 😃 Services could gravitate around paper reviews, public speaking, governance advice etc

**Comment by krrisis** [comment]
Great! Next: schedule in call between livia & kris to filter out what makes sense within our comms strategy for future steps. First step however is working on sharing what we are doing, starting with the newsletter which can be translated in a text for them, see #43 
We could start with a few experiments from the above after discussion.

**Comment by krrisis** [comment]
on hold until @GriffGreen & me have had a strategy sync call on the Trusted Seed

**Comment by jessicazartler** [comment]
#239
