### ISSUE TITLE
Polycentric Gov Gitbook

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#841]
## 📋   Anything to add?

The original TEC one is here: https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/292

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1yfAbB7-lKDjXXciGuHUr1vbPsTikhdMAxNFg8g1Ihac/edit

**Comment by jessicazartler** [comment]
Got some great feedback to split this into two articles.. sitting with publishing as is or breaking into two articles... ayyyy the writing process sometimes...

**Comment by jessicazartler** [comment]
Me trying to write/edit (yes all those tabs are research) 
![poly gov](https://user-images.githubusercontent.com/43972522/124518673-09502b00-ddb5-11eb-8cff-5a1cbc41f408.png)

Need time to go in my cave and finish

**Comment by jessicazartler** [comment]
This split into two articles:
An Introduction to Polycentric Governance Frameworks for Web3 
Exploring Governance Tools & Layers in the Token Engineering Commons 

@GriffGreen and I will work on it a bit together and discuss structure and where to publish - some parts will be published in the TEC Gitbook, the other research I am looking at publishing in a navigable HackMD/Gitbook because there is so much...

TBD after talks with Griff and some more work on it next week in Vienna

**Comment by jessicazartler** [comment]
I will be working with Burrrata to structure a HackMD navigable book to document all my research:
https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-book
https://hackmd.io/@hackmd-book-test/r1pFdZ_lK/https%3A%2F%2Fhackmd.io%2Fa0VuBJahRxmom-ZImjcW2g

For TEC tools, I will be working on getting the info into the TEC Gitbook - got the sign in details from @liviade1 and am scheduling a hack sesh for advice process on structure - creating a separate Github issue for that.

**Comment by jessicazartler** [comment]
ahhh! didn't see this -- dup https://github.com/commons-stack/iteration0/issues/993
