### ISSUE TITLE
Gitcoin Disputes Issues - Discussion

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#902]
## 📋   Anything to add?

Involved: @GriffGreen @Jeff-Emmett @jessicazartler @krisjpi 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
@krisjpi @GriffGreen Dani & Lauren in the Commons Simulator channel said they are keen to participate and handle the discussion - Kris I know you have a lot on your plate - perhaps connect with them and they can take lead and we can support - I think it makes more sense to have those on the Simulator team handle it, rather than CS team members with limited bandwidth

**Comment by krisjpi** [comment]
Both flags were resolved and closed with no action taken. For more detail, see the Round 10 Dispute summary sheet here: https://www.notion.so/e79f1dd9e5074a1d986ee3f91b12943e?v=022c87a9489449e6afb4600879595c7b

**Comment by jessicazartler** [comment]
Thank you @krisjpi !!!
